language: node_js
node_js:
- node
deploy:
  provider: s3
  access_key_id: AKIAUSNSPYXEK3XNHIGK
  secret_access_key:
    secure: Opp34iZ3IHyXUo5LR1n8kYf2xZJ/IJCasb+PQr26zCxW55p6xl0oGdb3sHKmEkDOcX88Ei0i0AU3odYqSMFlamx4tcE4UMO9J0w31E/mBiAd5rwdxV6KU+UQ90ebHGevxMINVEFAwkN0cbtoq8J/ustrJSc0w4Ne2THBynxw8o5+waf3QdBmh2gEJ0eNUFGeCPaviSZCg4llrN2kMV4Yui/MHuZvnqUdccN+oAHq5g6XtJBF4OKsu79j+QePUatOvhBix65GZzz+A6T0GyUcVNlol9gHkTBtOobyuFiCaPwJnpA98jhJm8ykgORdvknINT9yuxSMyCi5ubTtqshKavyjsinysosr62B293gCGd0Mi94s5tB20ihU8krB0b96vS5ej3P2CS0ZLbn2wOPSRol9WU4fjcYGD4SJ+zdMJJJ1pXHUuAuzDg7nCSlGjRcAM7bg7WY1d/khlsMkW/dRxEKAh5MsrGcaqRrRmlwEfnhjIXq4AcowoMU7mkvVJdTXcsZwENL7iX9ulgd7nMc9EfSWBGPQ13yLeT/spm2kT4XqBfVC5giFFun5q8jdb8i33YbVGTGtZIwMna51ZI+6eNQklBLZNrRJuQp2tjbfijtfirkaHfz2ArUjTNTakqt/oewl9gCgii9//81wQCL7nt0F1IhhOxb6kN9qPqddtVM=
  bucket: integration-sdk
