language: node_js
node_js:
  - node
deploy:
  provider: s3
  access_key_id: AKIAUSNSPYXEK3XNHIGK
  secret_access_key:
    secure: CRU7bxuFgVf07LxNMr3Db0zb06Z5gCMmkCfRj8iyPdc+3r/fP//3BSXPM+xYsrf2rC1E7SZ0wa98LkxIskkUgAGzAJiHrw2bWZVma58ySwr4Htx6EfjsPYgQzjTK/VZy88yHnZ26FmiGKZd7AUG+xULbFR1kmLJXB0S/rsiNaX6YehhKeM2fDqDO8Sm6oqZ2WY6016JrR8FNqDwHRGpp4WRpC4f/5JjU2kDNXxrnczbsvY98MAma1c7wWueAdT4k7E+A6zaAlWGbcdoAI5JT7MosU5HaevDcuHRBYRS+oPu/06Wi1NFZcvPMc+JV1HvPsuQLREwG0iMgbYKacPhsfmh5MxDv69TEY86r6h6O0Xp3KbLyKeKYWhuj2mJ5+9Y6SjWfTUGXEQ5onIC7dom+LJctg0IDs34cvyFcsG08jk+l7J8qxAFRmvFHW4UozwBOQPagsQ8JLOY3wrrVqRcolfahbcH9pnPGQJYsQXPdl4NnvnHC9tAUgwLJc155Z4v1a3jBSJ2XGwObkE5OK90DdVVSSrhnodGAVZUoa6IkhUnP2/nhq7EEMUgWmkYM0f1h7cHz/fbHzw+olPdZlS9onY/qrTyBky2KojzIL3DYu2hmatMgkcErkwli4zcfRfl8oJH89rrVvztN0/vY6zXjhzjIrjeAPfd2DkvrlYdTfJA=
  bucket: integration-sdk
