language: node_js
node_js:
- node
deploy:
  provider: s3
  access_key_id: AKIAUSNSPYXEK3XNHIGK
  secret_access_key:
    secure: RVcayUdxUukjqsz1SfRuIArDnCmo5YICIUX851Azgbo2Y+Fj4Ta/vYOK8irALrVvVxgjrjxQFyiTQldMiU8zB2IEDgMY9T6kKwR2nZ3K/0SY8pwCPEzlaulcxr9gZ1VFuH3i9Pk/0RPF7d4PlHUvUOKtbwYkUl3iBZghVY8lZsUJeS7YH0ATTB0OG+0M0Mn85z7JXy0Yl7zRPcO6mSQNaHyZwZoJMn5pcSefjkJO5MbiZvp5DcGS/3iP5ygEAfgDXnPOgjqPqnNWw/DsTAAWdc39mubTQvaWF3rMeVwX2D3lUSEG45SA0lQ+HF7kqDs3Nr7YYkNyZsB+bEcUSztWLMP5JimOx+584DU01Q4Ja/pX4X0JQcozkZmpCrN0eUQ8UQPp2pk5O8HnPtOMyRR3WXrBOwrWjH6wEkKCeFgKhtpz7Zs3VrQj0othmb9wJuZLO7TciBBNMr8rRvO4wa+DQepvLDqL2m/mH/tOodDt2a1jqZthAIGaaiUUOmm7yqdvLJFzbTanwCjj/Ggc7s0+S+0r5Yvp4rluGBbFoGJrW9tqetZoLVgl6vhULdMkFdGxgwOvDl1I4reqr3N+Nsz95mozJSaJR5sLJVPdrvDK4/EMCrFa3KEzpAslRcazBdOsjZICDk/XnZrASgS40PwoY3yd674Dej1EFg4d8cOJI0o=
  bucket: integration-sdk
