language: node_js
node_js:
  - node
deploy:
  provider: s3
  access_key_id: AKIAUSNSPYXENENSH7ML
  secret_access_key:
    secure: Wa9WgWjcTtXCPnmqyoorBFRlROPRjggVdV57mJDYJy2bJVWl2xhB5ZMMQ6efMUB7FTV53Z54z6Ht6vKsOYN2Wq4Kb6EvSU0WMK3QAl2fwh1+av+LOFrgyFNxyQLRxi/jnUgTamdWGkUftlHXZ8fbGFkuEHVpwKFc2UwpSOHL+FJup6XbCNpv9YBR4H2B8ArEi7tLF4X648+8FNQQTkJkmoSY80n/uVRc/jvVHZyVXyKn5JvpB4U2du5e8HL35eHjfAWyBTNNySS2vGDwt4KT98X2f/n2L/CkzlGx7XEKRmnUvdwndGJeJvHZ2ZLyrM16hg6vyfujOEecCBaZp+bpnixnIx+CYoQ9TTxUzgW7jkt3bugFegIQAlKSuKwuLX/z1BzmUbvtn3791XANpcP6D7dcrxpjPH3GmFIgvAslGs48UjS+tl6NgP4BcMwXeutYUVcCVt4ThQ5Jgn9cx7c7sI03qaSEOyGrJbHGDlqrmFyeGRbr05t2aRybLOeXMsScZIhLE0iRaebneMI04MQBN5A0oSbr+agLN/GEL+CYpVsE1PRsvIv0+gr1MI+FWqYq1ZEIW+jtfSvgkOP5xoPCFMjUEzV6h447LcRHQoHyvDmZo3nycar9NN7tfeIgCHkQpiNNGWhuQoU05iJRYXWq0jiAhzTj/0YhwkduW6WN6OI=
  bucket: external-integration
  skip_cleanup: true
  local_dir: scripts
  upload-dir: $UPLOAD_DIR
  detect_encoding: true
  on:
    repo: privyr/integration-sdk
    branch: develop