language: node_js
node_js:
- node
deploy:
  provider: s3
  access_key_id: AKIAUSNSPYXEK3XNHIGK
  secret_access_key:
    secure: POdnfPT20G1Uvj7FNvCsKQRzAtgaQWMtgikvq4ux6JnXZ/hTcWIrSXNif5JZaCpDYEnFV6fJ12mYcW+XoL4hmNGbhRW0O/MJzQ9tWBFK6KKrUGRm5yo1yEgdzGvcqPYrzI6CP/7f0Tu8tx0hyt2MttGI4lMRquS3synRJ/+ymXPi2hlHkFKOSWMxPJM0ll5Ls1fDvmC+qnBfxdGiPd/h6Wm0NfK1wMK20SzMeXUvpyRtHKt70d/iLMj1pVFoO4L/meKnkFF1zxm6rWGtU/lclEycwgyzuubQJZhYnWdbMEtd889CPAQQPd7veXZC/g5WyaxDzlp5T9bnZ3m8mB1KnSR6WkfgFqERf2uKy6aUKd0Q9yNvJcQK/CeuBFs8wJ71ORv9rKCJD+v8K491gmgltfbTsFB0S5PnnhKoWiHpbNZtNdDF5MNrVEDq4ZTuEEZ5ZF/PAIB1yKkEptLg813yXOGVdtPezQfX7PRAqdwQEsCXV6tIYQtGh1VYFcvd/n9U4rEBG3LMYow6H/s+VoPvewJWamdgi6/BosatAA2n3unFTgUp7NxIGqne0BPllLB1/M23LY1F2O5AhfgRAgZoMRMuY2LmC8PkDOGWZ/3dYA+9qY0h5ilNUy6zF0X21wgn/otMRcQCQ4H8ipBB20ts6cpqQk0OL4kPfhTGPh7TZK8=
  bucket: external-integration
